/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiDialogSearch: typeof import('./src/components/AiDialogSearch.vue')['default']
    DialogSearch: typeof import('./src/components/DialogSearch.vue')['default']
    DynamicLongPeopleCard: typeof import('./src/components/peopleCard/DynamicLongPeopleCard.vue')['default']
    HeaderCatalog: typeof import('./src/components/HeaderCatalog.vue')['default']
    HeroCard: typeof import('./src/components/HeroCard.vue')['default']
    LangSwitcher: typeof import('./src/components/LangSwitcher.vue')['default']
    ListFolded: typeof import('./src/components/ListFolded.vue')['default']
    LongPeopleCard: typeof import('./src/components/peopleCard/LongPeopleCard.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortPeopleCard: typeof import('./src/components/peopleCard/ShortPeopleCard.vue')['default']
    SimpleCard: typeof import('./src/components/SimpleCard.vue')['default']
  }
}
